# test that missing return from a branch doesn't generate an error if there's a subsequent return
f := () -> int {
	if (42 != 42) {
		return 1
	} else {
	}
	return 2
}
